name: On Tag, Trigger GitHub Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:

  push-test:
    name: Build and Push Test
    uses: unbounded-tech/workflows-containers/.github/workflows/publish.yaml@main
    with:
      dockerfiles: |
        [
          {"dockerfile":"./test/test-1.Dockerfile","context":"./test","prefix":"test1-"},
          {"dockerfile":"./test/test-2.Dockerfile","postfix":"test2"}
        ]
      push: true

  release:
    needs: push-test
    uses: unbounded-tech/workflow-simple-release/.github/workflows/workflow.yaml@v2.0.1
    with:
      tag: ${{ github.ref_name }}
      name: ${{ github.ref_name }}
